ifpebj-ti/horas-discentes

teste.txt

Adicionei o início do formulário para os discentes enviarem seus comprovantes de horas aula.

feat: adiciona arquivo de teste

---

README.md

docs: adiciona README inicial

---

.github/workflows/ci.yml

ci: adiciona workflow de verificação automática

Workflow de Verificação Automática

---

Back/Dockerfile
docker-compose.yml
front/Dockerfile
front/package-lock.json
front/package.json
front/src/app/page.tsx

Adição da Aplicação Conteinerizada e a Guia de Execuçao de Configuração usando Docker e Docker Compose

feat: Adição da Aplicação Conteinerizada e a Guia de Execução 

---

front/src/app/(coordenador)/coordenacao/contabilizarHoras/page.tsx
front/src/app/(coordenador)/coordenacao/turma/page.tsx
front/src/components/FormRegistroHoras/index.tsx
front/src/components/ui/SelectBox.tsx

Tela de turmas, secretaria e ajuste de select da categorias

novas telas e ajustes

---

Back/teste-release.txt

Adiciona arquivo de teste para validação de release

---

Back/teste-release.txt

Atualiza mensagem de teste para validação de release

---

horas-discentes/docker-compose.yml

Corrige docker-compose.yml para Portainer

---

front/src/app/(admin)/curso/page.tsx

Es fix curso

---

Back/Back.API/Program.cs

fix: habilitar Swagger em produção

---

docker-compose.yml

Correções no arquivo compose

---

Back/Back.API/Program.cs
docker-compose.yml

Correções no arquivo Program.cs

---

Back/Back.API/Program.cs

Correções no arquivo Program.cs para integração do db

---

docker-compose.yml

Correção do compose

---

Back/Back.API/Back.http

Correção no arquivo Back.http

---

docker-compose.yml

Correção no arquivo compose.yml

---

nginx/nginx.conf

Atualiza configurações do NGINX para proxy e SSL

---

nginx/nginx.conf

Correção no arquivo Nginx

---

.env
docker-compose.yml
nginx/default.conf
nginx/nginx.conf

Aletrações no docker

---

.github/workflows/ci-backend.yml
.github/workflows/ci-cd.yml
.github/workflows/ci-frontend.yml
Back/Dockerfile

Correções nos arquivos ci-cd do back e front

---

.github/workflows/ci-cd.yml
.github/workflows/ci-frontend.yml

Correções no CI-CD

---

.github/workflows/ci-cd.yml

Correções no CI-CD novamente

---

.github/workflows/ci-cd.yml

Correções no CI-CD com alterações no back

---

.github/workflows/ci-cd.yml

Novas atualizações do ci-cd

---

.github/workflows/ci-cd.yml

Atualização 5

---

.github/workflows/ci-cd.yml

Atualização 7

---

.github/workflows/ci-backend.yml
.github/workflows/ci-cd.yml
.github/workflows/ci-frontend.yml

Atualização 8

---

.github/workflows/ci-cd.yml

Atualização 9

---

.github/workflows/ci-cd.yml

Atualização 10

---

.github/workflows/ci-cd.yml

Atualização 13

---

.github/workflows/ci-cd.yml

Atualização 14

---

docker-compose.yml

feat: Atualiza docker-compose para usar imagens do GHCR

---

nginx/back.conf
nginx/front.conf

Atualização 17

---

docker-compose.yml

Atualização 18

---

.env

Atualização 19

---

docker-compose.yml

atualização 21

---

docker-compose.yml

Atualização 23

---

nginx/conf.d/back.conf
nginx/conf.d/front.conf

Atualização 24

---

nginx/conf.d/default-ssl.conf

Atualização 27

---

.env
.gitignore
docker-compose.yml

Atualização 29

---

front/src/lib/authOptions.ts

Update API URL for authentication login
